"""ESA Host Brief — CLI for generating run briefs from incentive spreadsheet + SRC.

Usage:
    python3 -m src.brief <subcommand> [args]

Subcommands:
    picker            Interactive pick list of upcoming runs
    runs              Filter runs by window/next/marathon
    research          SRC categories, records, WR deltas for a game
    research-runner   SRC runner profile + personal-bests lookup
    past-esa          Find past ESA appearances (lineup + horaro fallback)
    runner-profile    Composite stats: summary + detailed stats block
    siblings          ESA sibling runs for a runner
    cache-developer   Read/write developer cache entries
    find-siblings     Schedule games by the same developer
    write             Write markdown brief + JSON sidecar
    orphans           Check and mark orphaned brief files
    stale             Check spreadsheet staleness

Output files:
    output/briefs/<slug>.md
    output/briefs/<slug>.json
    output/briefs/.cache/developers.json

Source data:
    output/incentive_plan.xlsx  (generated by eso-pipeline)
"""

import argparse
import json
import os
import re
import sys
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

from . import brief_builder as bb
from . import xlsx_reader as xr
from .horaro import fetch_schedule, list_event_schedules, parse_iso_duration
from .slugs import run_slug, shift_dir_slug
from .src_api import (
    search_src_game,
    fetch_src_categories,
    fetch_game_records,
    search_user_by_lookup,
    fetch_user_personal_bests,
    fetch_user_profile,
    SrcApiError,
)

SPREADSHEET_PATH = "output/incentive_plan.xlsx"
BRIEFS_DIR = "output/briefs"
CACHE_DIR = "output/briefs/.cache"
DEVELOPER_CACHE_PATH = os.path.join(CACHE_DIR, "developers.json")
PAST_EVENTS_CACHE_PATH = os.path.join(CACHE_DIR, "past_events.json")
LINEUP_CACHE_PATH = os.path.join(CACHE_DIR, "lineup.json")
RUNNER_PROFILE_CACHE_PATH = os.path.join(CACHE_DIR, "runner_profiles.json")
TZ = ZoneInfo("Europe/Stockholm")

# Authoritative past-ESA source — hosted by the marathon's own lineup
# tracker. Cache the full payload on disk (24h TTL) so the 2,800-person
# dataset doesn't get re-fetched per brief.
LINEUP_API_URL = "https://lineup.esamarathon.dev/api/public"
LINEUP_TTL_HOURS = 24

# runner_profiles.json holds per-runner composite profiles keyed by
# "{twitch}|{name_lower}". Entries are JSON blobs with a `fetched_at`
# timestamp so the CLI can skip a refresh within the TTL window.
RUNNER_PROFILE_TTL_HOURS = 24 * 7  # 7 days — info changes rarely

# A small subset of the runner profile fields is safe to refresh on
# every brief (PB count, current SRC signup, event count from
# lineup). But the disk cache avoids a hot path. This is the floor —
# `--refresh` overrides it.

# Runners in the current marathon are commonly also members of these
# ESA-adjacent communities. We match against the SRC `aboutme` field
# and the runner's Twitch bio. Lowercase; the comparator strips
# punctuation, so a regex like "sesa" matches "SESA", "S.E.S.A", etc.
KNOWN_COMMUNITIES = [
    {"name": "SESA", "patterns": [r"\bsesa\b", r"s[\W_]*e[\W_]*s[\W_]*a[\W_]*b"]},
    {"name": "ESA Staff", "patterns": [r"\besa[\W_]+staff\b", r"\besa[\W_]+crew\b"]},
    {"name": "GDQ", "patterns": [r"\bgdq\b", r"games[\W_]+done[\W_]+quick"]},
    {"name": "Speed Demos Archive", "patterns": [r"\bsda\b", r"speed[\W_]+demos[\W_]+archive"]},
    {"name": "Speedrun.com", "patterns": [r"\bspeedrun\.com\b", r"\bsrc\b"]},
    {"name": "Maritime speedrunning", "patterns": [r"\bmaritime\b"]},
    {"name": "RTA in Japan", "patterns": [r"\brta[\W_]+in[\W_]+japan\b", r"\brtaij\b"]},
]

# Twitch `aboutme` markers that imply a team/community membership line.
_TEAM_LINE_RE = re.compile(
    r"^\s*(?:team|community|guild|clan|org)[\s:]+(.+?)\s*$",
    re.IGNORECASE | re.MULTILINE,
)


def _load_dotenv() -> None:
    """Load .env file into os.environ if it exists.

    Mirrors the loader in src/pipeline.py so the brief CLI can read
    HORARO_PAST_SCHEDULES, HORARO_ORG, etc. without the agent having
    to export them manually.
    """
    env_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), ".env")
    if not os.path.exists(env_path):
        return
    with open(env_path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key and key not in os.environ:
                os.environ[key] = value


_load_dotenv()


# ── helpers ──────────────────────────────────────────────────────────────────


def _now() -> datetime:
    return datetime.now(TZ)


def _load_developer_cache() -> dict[str, str]:
    os.makedirs(CACHE_DIR, exist_ok=True)
    if not os.path.exists(DEVELOPER_CACHE_PATH):
        return {}
    try:
        with open(DEVELOPER_CACHE_PATH) as f:
            data = json.load(f)
            if not isinstance(data, dict):
                return {}
            return data
    except (json.JSONDecodeError, OSError):
        # Corrupt cache — back it up and start fresh
        backup = DEVELOPER_CACHE_PATH + ".corrupt-" + _now().strftime("%Y%m%dT%H%M%S")
        try:
            os.rename(DEVELOPER_CACHE_PATH, backup)
        except OSError:
            pass
        return {}


def _save_developer_cache(cache: dict[str, str]) -> None:
    os.makedirs(CACHE_DIR, exist_ok=True)
    with open(DEVELOPER_CACHE_PATH, "w") as f:
        json.dump(cache, f, indent=2)


# ── past-event cache ────────────────────────────────────────────────────────
# Caches the list of past Horaro slugs (refreshed when missing or older
# than 24h). The list is small and stable so re-listing is cheap; we
# only avoid hitting horaro on every brief in a batch run.


def _load_past_events_cache() -> dict:
    """Return cached past-event metadata: {fetched_at, schedules: [...]}."""
    if not os.path.exists(PAST_EVENTS_CACHE_PATH):
        return {}
    try:
        with open(PAST_EVENTS_CACHE_PATH) as f:
            data = json.load(f)
            if not isinstance(data, dict):
                return {}
            return data
    except (json.JSONDecodeError, OSError):
        return {}


def _save_past_events_cache(schedules: list[dict]) -> None:
    os.makedirs(CACHE_DIR, exist_ok=True)
    payload = {
        "fetched_at": _now().isoformat(),
        "schedules": schedules,
    }
    with open(PAST_EVENTS_CACHE_PATH, "w") as f:
        json.dump(payload, f, indent=2)


def _past_event_schedules(org: str, exclude_slugs: set[str], max_age_hours: float = 24) -> list[dict]:
    """Return all Horaro schedules under `org` minus `exclude_slugs`.

    Results are cached on disk for `max_age_hours` so a 200-run batch
    doesn't hammer horaro.net. The list is small (~50 events for ESA)
    so a single re-fetch per day is cheap.
    """
    cache = _load_past_events_cache()
    fetched_at = cache.get("fetched_at")
    schedules = cache.get("schedules", [])
    fresh = False
    if fetched_at:
        try:
            age = _now() - datetime.fromisoformat(fetched_at)
            fresh = age.total_seconds() < max_age_hours * 3600
        except ValueError:
            fresh = False
    if not fresh or not schedules:
        try:
            schedules = list_event_schedules(org)
            _save_past_events_cache(schedules)
        except Exception:
            # Fall back to whatever's in the cache (even if stale)
            schedules = cache.get("schedules", [])
    return [s for s in schedules if s.get("slug") and s["slug"] not in exclude_slugs]


# ── lineup.esamarathon.dev cache ─────────────────────────────────────────────
# This is the marathon's own attendee tracker — authoritative for
# past-ESA counts, twitch handles, and country. The full payload
# (~360KB, ~2,800 people) is cached on disk for 24h. Per-runner lookups
# happen in-memory against the cached payload.


def _load_lineup_cache() -> dict:
    """Return the cached lineup payload, refreshing if stale or missing.

    Schema:
        {
          "fetched_at": ISO timestamp,
          "people": [...],         # raw lineup records
          "by_twitch": {twitch_lower: [indices]},
          "by_name":   {name_lower:  [indices]},
        }
    """
    os.makedirs(CACHE_DIR, exist_ok=True)
    if os.path.exists(LINEUP_CACHE_PATH):
        try:
            with open(LINEUP_CACHE_PATH) as f:
                data = json.load(f)
            if isinstance(data, dict) and data.get("people"):
                fetched_at = data.get("fetched_at")
                if fetched_at:
                    try:
                        age = _now() - datetime.fromisoformat(fetched_at)
                        if age.total_seconds() < LINEUP_TTL_HOURS * 3600:
                            return data
                    except ValueError:
                        pass
        except (json.JSONDecodeError, OSError):
            pass

    # Fetch fresh from lineup.esamarathon.dev
    import urllib.request
    try:
        req = urllib.request.Request(
            LINEUP_API_URL,
            headers={"User-Agent": "esa-brief-skill/0.1 (host briefing tool)"},
        )
        with urllib.request.urlopen(req, timeout=30) as resp:  # nosec B310
            payload = json.loads(resp.read().decode("utf-8"))
    except Exception as e:
        # Network down — try the stale cache as a last resort
        if os.path.exists(LINEUP_CACHE_PATH):
            try:
                with open(LINEUP_CACHE_PATH) as f:
                    data = json.load(f)
                if isinstance(data, dict) and data.get("people"):
                    return data
            except (json.JSONDecodeError, OSError):
                pass
        return {"fetched_at": _now().isoformat(), "people": [],
                "by_twitch": {}, "by_name": {}, "error": str(e)}

    people = payload.get("people", []) or []
    by_twitch: dict[str, list[int]] = {}
    by_name: dict[str, list[int]] = {}
    for i, p in enumerate(people):
        tw = (p.get("twitch") or "").strip().lower()
        if tw:
            by_twitch.setdefault(tw, []).append(i)
        nm = (p.get("name") or "").strip().lower()
        if nm:
            by_name.setdefault(nm, []).append(i)

    out = {
        "fetched_at": _now().isoformat(),
        "people": people,
        "by_twitch": by_twitch,
        "by_name": by_name,
    }
    try:
        with open(LINEUP_CACHE_PATH, "w") as f:
            json.dump(out, f, indent=2)
    except OSError:
        # Cache is best-effort; we still return the in-memory payload
        pass
    return out


def _lineup_lookup(lineup: dict, name: str, twitch: str) -> list[dict]:
    """Return all lineup records matching name+twitch (OR semantics).

    Twitch match wins when both are present — the lineup is keyed
    primarily by twitch. A name-only match is returned as a fallback
    for runners without a twitch handle on the lineup.
    """
    people = lineup.get("people", [])
    by_twitch = lineup.get("by_twitch", {})
    by_name = lineup.get("by_name", {})
    name_lower = (name or "").strip().lower()
    twitch_lower = (twitch or "").strip().lower()

    if twitch_lower and twitch_lower in by_twitch:
        return [people[i] for i in by_twitch[twitch_lower]]
    if name_lower and name_lower in by_name:
        return [people[i] for i in by_name[name_lower]]
    return []


# ISO 3166-1 alpha-2 / alpha-3 -> English short name. Curated subset
# covering every country in the lineup dataset. Falls back to the
# upper-cased code if unknown.
_COUNTRY_NAMES = {
    "ad": "Andorra", "ae": "United Arab Emirates", "ar": "Argentina", "at": "Austria",
    "au": "Australia", "ba": "Bosnia and Herzegovina", "be": "Belgium", "bg": "Bulgaria",
    "br": "Brazil", "ca": "Canada", "ch": "Switzerland", "cl": "Chile", "cn": "China",
    "co": "Colombia", "cr": "Costa Rica", "cz": "Czechia", "de": "Germany", "dk": "Denmark",
    "ec": "Ecuador", "ee": "Estonia", "eg": "Egypt", "es": "Spain", "fi": "Finland",
    "fo": "Faroe Islands", "fr": "France", "gb": "United Kingdom", "gbr": "United Kingdom",
    "gr": "Greece", "hk": "Hong Kong", "hr": "Croatia", "hu": "Hungary", "id": "Indonesia",
    "ie": "Ireland", "il": "Israel", "im": "Isle of Man", "in": "India", "ir": "Iran",
    "is": "Iceland", "it": "Italy", "jp": "Japan", "kr": "South Korea", "kw": "Kuwait",
    "lt": "Lithuania", "lu": "Luxembourg", "lv": "Latvia", "ma": "Morocco", "mc": "Monaco",
    "me": "Montenegro", "mk": "North Macedonia", "mt": "Malta", "mx": "Mexico", "my": "Malaysia",
    "nl": "Netherlands", "nld": "Netherlands", "no": "Norway", "nz": "New Zealand",
    "pe": "Peru", "ph": "Philippines", "pl": "Poland", "pt": "Portugal", "ro": "Romania",
    "rs": "Serbia", "ru": "Russia", "sa": "Saudi Arabia", "se": "Sweden", "sg": "Singapore",
    "si": "Slovenia", "sk": "Slovakia", "th": "Thailand", "tr": "Turkey", "tw": "Taiwan",
    "ua": "Ukraine", "uk": "United Kingdom", "us": "United States", "usa": "United States",
    "uy": "Uruguay", "ve": "Venezuela", "vn": "Vietnam", "za": "South Africa",
}


def _country_name(code: str) -> str:
    """Return the English short name for an ISO country code, or the code itself."""
    if not code:
        return ""
    return _COUNTRY_NAMES.get(code.lower(), code.upper())


# ── runner profile cache ─────────────────────────────────────────────────────
# Per-runner composite profiles, keyed by "{twitch}|{name_lower}".
# Each entry has a `fetched_at` so the CLI can skip a refresh inside
# the TTL window. The on-disk cache is also the source of truth for
# the SQLite `runner.stats_json` column during import — we don't
# re-fetch lineup/SRC during a re-import, we just read the cached
# profile and copy it in.


def _runner_profile_key(twitch: str, name: str) -> str:
    """Stable cache key. Twitch wins because lineup is twitch-keyed."""
    tw = (twitch or "").strip().lower()
    nm = (name or "").strip().lower()
    return f"{tw}|{nm}"


def _load_runner_profile_cache() -> dict:
    """Return the on-disk runner-profile cache, or {} if missing/corrupt."""
    if not os.path.exists(RUNNER_PROFILE_CACHE_PATH):
        return {}
    try:
        with open(RUNNER_PROFILE_CACHE_PATH) as f:
            data = json.load(f)
            if not isinstance(data, dict):
                return {}
            return data
    except (json.JSONDecodeError, OSError):
        return {}


def _save_runner_profile_cache(cache: dict) -> None:
    os.makedirs(CACHE_DIR, exist_ok=True)
    try:
        with open(RUNNER_PROFILE_CACHE_PATH, "w") as f:
            json.dump(cache, f, indent=2)
    except OSError:
        # Best-effort; we still serve the in-memory profile
        pass


def _runner_profile_is_fresh(entry: dict) -> bool:
    """True if a cached profile is inside the TTL window."""
    fetched_at = entry.get("fetched_at")
    if not fetched_at:
        return False
    try:
        age = _now() - datetime.fromisoformat(fetched_at)
    except ValueError:
        return False
    return age.total_seconds() < RUNNER_PROFILE_TTL_HOURS * 3600


def _extract_tenure(signup: str | None) -> dict:
    """Compute streaming tenure from an SRC `signup` ISO timestamp.

    Returns years (int), years_label ("5 years"), display_date
    (YYYY-MM-DD), and an "unavailable" flag if signup is missing.
    """
    if not signup:
        return {
            "available": False,
            "signup": None,
            "years": None,
            "label": "Not found — ask the runner.",
        }
    try:
        signup_dt = datetime.fromisoformat(signup.replace("Z", "+00:00"))
    except ValueError:
        return {
            "available": False,
            "signup": signup,
            "years": None,
            "label": "Not found — ask the runner.",
        }
    now = _now()
    if signup_dt.tzinfo is not None:
        now = now.replace(tzinfo=signup_dt.tzinfo)
    delta_days = (now - signup_dt).days
    years = max(0, delta_days // 365)
    return {
        "available": True,
        "signup": signup_dt.date().isoformat(),
        "years": years,
        "label": f"{years} year{'s' if years != 1 else ''} on speedrun.com (since {signup_dt.date().isoformat()})",
    }


def _extract_communities(aboutme: str | None, twitch_bio: str | None) -> list[dict]:
    """Scan SRC aboutme + Twitch bio for community markers.

    Returns a list of {name, source, evidence}. Each match is anchored
    by a literal pattern from KNOWN_COMMUNITIES; the evidence line
    shows the matched substring (truncated).
    """
    sources: list[tuple[str, str | None]] = [
        ("speedrun.com", aboutme or ""),
        ("twitch", twitch_bio or ""),
    ]
    found: list[dict] = []
    seen: set[tuple[str, str]] = set()
    for source_name, text in sources:
        if not text:
            continue
        text_lower = text.lower()
        for community in KNOWN_COMMUNITIES:
            for pat in community["patterns"]:
                m = re.search(pat, text_lower, re.IGNORECASE)
                if not m:
                    continue
                key = (source_name, community["name"])
                if key in seen:
                    continue
                seen.add(key)
                # Pull a small window of the original text for evidence.
                start = max(0, m.start() - 20)
                end = min(len(text), m.end() + 30)
                evidence = text[start:end].strip()
                if len(evidence) > 80:
                    evidence = evidence[:77] + "..."
                found.append({
                    "name": community["name"],
                    "source": source_name,
                    "evidence": evidence,
                })
                break  # one match per community per source is enough
    return found


def _render_picker_list(runs: list[xr.RunRow], now: datetime) -> dict:
    """Build the interactive picker JSON response."""
    result = {
        "now_stockholm": now.isoformat(),
        "runs": [],
    }
    for r in runs:
        status = "upcoming"
        if r.scheduled < now and (now - r.scheduled).total_seconds() < 7200:
            status = "recently-completed"
        result["runs"].append({
            "pick": r.pick,
            "scheduled": r.scheduled.isoformat(),
            "status": status,
            "game": r.game,
            "category": r.category,
            "estimate": r.estimate,
            "runner": r.runner_display,
            "stream": xr.stream_token_to_short(r.stream),
        })
    return result


def _load_runs(args) -> list[xr.RunRow]:
    """Load runs from the configured source (xlsx or db)."""
    source = getattr(args, "source", "xlsx") or "xlsx"
    if source == "db":
        db_path = getattr(args, "db_path", "") or "output/esa.db"
        return xr.read_cross_reference_from_db(db_path)
    return xr.read_cross_reference(args.spreadsheet)


def _load_incentives(args) -> list[xr.IncentiveRow]:
    """Load incentives from the configured source (xlsx or db)."""
    source = getattr(args, "source", "xlsx") or "xlsx"
    if source == "db":
        db_path = getattr(args, "db_path", "") or "output/esa.db"
        return xr.read_incentives_from_db(db_path)
    return xr.read_incentives(args.spreadsheet)


def _resolve_runs(
    args,
    max_upcoming: int = 50,
) -> list[xr.RunRow]:
    """Load runs from configured source and apply filters."""
    all_runs = _load_runs(args)
    now = _now()

    stream_token = getattr(args, "stream", "")
    if stream_token:
        all_runs = xr.filter_runs_by_stream(all_runs, stream_token)

    if getattr(args, "marathon", False):
        return all_runs

    if getattr(args, "window", None):
        start_str, end_str = args.window.split("/")
        start = datetime.fromisoformat(start_str)
        end = datetime.fromisoformat(end_str)
        return xr.filter_runs_by_window(all_runs, start, end)

    next_hours = getattr(args, "next_hours", 0)
    if next_hours:
        start = now
        end = now + timedelta(hours=next_hours)
        return xr.filter_runs_by_window(all_runs, start, end)

    # Default: upcoming only, capped
    upcoming = [r for r in all_runs if not r.scheduled < now - timedelta(hours=2)]
    upcoming.sort(key=lambda r: r.scheduled)
    return upcoming[:max_upcoming]


def _ensure_dirs() -> None:
    os.makedirs(BRIEFS_DIR, exist_ok=True)
    os.makedirs(CACHE_DIR, exist_ok=True)


# ── subcommand implementations ───────────────────────────────────────────────


def cmd_picker(args) -> None:
    """Return numbered run list for interactive picker."""
    runs = _resolve_runs(args)
    result = _render_picker_list(runs, _now())
    if not result["runs"]:
        # No upcoming runs — show the next run after now
        all_runs = _load_runs(args)
        now = _now()
        future = [r for r in all_runs if r.scheduled >= now]
        future.sort(key=lambda r: r.scheduled)
        if future:
            result["next_run"] = {
                "scheduled": future[0].scheduled.isoformat(),
                "game": future[0].game,
                "category": future[0].category,
                "estimate": future[0].estimate,
            }
    print(json.dumps(result, indent=2))


def cmd_runs(args) -> None:
    """Return filtered run rows as JSON."""
    runs = _resolve_runs(args)
    print(json.dumps([
        {
            "pick": r.pick,
            "scheduled": r.scheduled.isoformat(),
            "game": r.game,
            "category": r.category,
            "estimate": r.estimate,
            "platform": r.platform,
            "stream": r.stream,
            "stream_short": xr.stream_token_to_short(r.stream),
            # Flat fields kept for transitional compat (from participants[0]).
            "runner_display": r.runner_display,
            "runner_twitch": r.runner_twitch,
            "runner_discord": r.runner_discord,
            "runner_twitter": r.runner_twitter,
            "commentator": r.commentator,
            "pronouns": r.pronouns,
            "show_cam": r.show_cam,
            "incentives": r.incentives,
            "submission_id": r.submission_id,
            "layout": r.layout,
            # Multi-runner participants list.
            "participants": r.participants or [],
        }
        for r in runs
    ], indent=2))


def cmd_research(args) -> None:
    """Fetch SRC categories + records + WR deltas for a game."""
    game_name = args.game
    current_category = args.category or ""
    estimate_min = args.estimate_min or 0

    result = {
        "game": game_name,
        "category": current_category,
        "srcext_game": {},
        "categories": [],
        "records": [],
        "estimate_seconds": estimate_min * 60,
    }

    game = search_src_game(game_name)
    if not game:
        print(json.dumps(result, indent=2))
        return

    game_id = game["id"]
    abbr = game.get("abbreviation", "")
    src_url = f"https://www.speedrun.com/{abbr}" if abbr else ""

    result["srcext_game"] = {
        "id": game_id,
        "name": (game.get("names", {}) or {}).get("international", ""),
        "abbreviation": abbr,
        "src_url": src_url,
    }

    try:
        cats = fetch_src_categories(game_id)
        result["categories"] = [
            {
                "id": c["id"],
                "name": c["name"],
                "type": c.get("type", ""),
            }
            for c in cats
        ]
    except SrcApiError:
        result["category_error"] = "Failed to fetch categories"

    try:
        records = fetch_game_records(game_id)
        result["records"] = records
    except SrcApiError:
        result["record_error"] = "Failed to fetch records"

    print(json.dumps(result, indent=2))


def cmd_research_runner(args) -> None:
    """Look up runner profile on SRC with tiered verification.

    Extended output (still backwards compatible — new keys are additive):
      - `signup`, `aboutme`, `location`: raw fields from /users/{id}
      - `tenure`: derived years-on-SRC dict (see _extract_tenure)
    """
    twitch = args.twitch or ""
    name = args.name or ""

    result = {
        "verified": False,
        "confidence": None,
        "profile": None,
        "personal_bests": [],
        "twitch_matched": False,
        "name_matched": False,
        "src_url": None,
        "signup": None,
        "aboutme": None,
        "location": None,
        "tenure": {"available": False, "signup": None, "years": None,
                    "label": "Not found — ask the runner."},
    }

    try:
        user = search_user_by_lookup(twitch) or search_user_by_lookup(name)
    except SrcApiError:
        print(json.dumps(result, indent=2))
        return
    if not user:
        print(json.dumps(result, indent=2))
        return

    user_id = user.get("id", "")
    user_name = (user.get("names", {}) or {}).get("international", "")
    user_twitch_uri = (user.get("twitch", {}) or {}).get("uri", "") if user.get("twitch") else ""
    src_url = f"https://www.speedrun.com/users/{user_name}" if user_name else None

    # Tiered verification
    twitch_matched = bool(twitch and twitch.lower() in user_twitch_uri.lower())
    name_matched = bool(name and user_name.lower() == name.lower())

    confidence = None
    if twitch_matched:
        confidence = "high"
    elif name_matched:
        confidence = "moderate"
    else:
        # Discard — can't verify
        print(json.dumps(result, indent=2))
        return

    result["verified"] = True
    result["confidence"] = confidence
    result["profile"] = {
        "id": user_id,
        "display_name": user_name,
        "weblink": user.get("weblink"),
        "twitch_uri": user_twitch_uri,
    }
    result["twitch_matched"] = twitch_matched
    result["name_matched"] = name_matched
    result["src_url"] = src_url

    # Pull extra fields (signup, aboutme, location) from /users/{id}.
    # The lookup response can omit these, so we make a second call.
    profile = None
    try:
        profile = fetch_user_profile(user_id)
    except SrcApiError:
        profile = None
    if profile:
        result["signup"] = profile.get("signup")
        aboutme = profile.get("aboutme")
        if aboutme and isinstance(aboutme, str):
            # Trim to keep the JSON small — full bio is rarely needed.
            result["aboutme"] = aboutme if len(aboutme) <= 1000 else aboutme[:997] + "..."
        loc = profile.get("location")
        if isinstance(loc, dict):
            country = ((loc.get("country") or {}).get("names") or {}).get("international", "")
            region = ((loc.get("region") or {}).get("names") or {}).get("international", "")
            if country or region:
                result["location"] = ", ".join(p for p in (region, country) if p)

    result["tenure"] = _extract_tenure(result["signup"])

    try:
        pbs = fetch_user_personal_bests(user_id)
        seen_games: dict[str, dict] = {}
        for pb in pbs:
            gname = pb["game_name"]
            if gname not in seen_games:
                seen_games[gname] = {
                    "game_name": gname,
                    "game_abbr": pb["game_abbr"],
                    "times": [],
                }
            seen_games[gname]["times"].append({
                "time_seconds": pb["time_seconds"],
            })
        result["personal_bests"] = list(seen_games.values())
    except (SrcApiError, Exception):
        pass

    print(json.dumps(result, indent=2))


def _csv_env(name: str, default: str = "") -> list[str]:
    """Return a comma-separated env var as a list of stripped values."""
    raw = os.getenv(name, default) or ""
    return [v.strip() for v in raw.split(",") if v.strip()]


def _first_event_year(events: list[str]) -> int | None:
    """Extract the earliest 4-digit year from lineup event labels.

    Lineup events look like "ESA 2017", "ESA Summer 2022",
    "ESA Winter 2018". Pulls the first 19xx/20xx year found.
    """
    if not events:
        return None
    years: list[int] = []
    for e in events:
        m = re.search(r"\b((?:19|20)\d{2})\b", e or "")
        if m:
            years.append(int(m.group(1)))
    return min(years) if years else None


def _horaro_past_appearances(name: str, twitch: str, org: str = "") -> dict:
    """Return {events, matches, first_appearance, error} from Horaro only.

    Used as a fallback when lineup.esamarathon.dev has no record.
    Walks the org's past Horaro schedules (excluding the current
    marathon's slugs) and matches players cell by name + twitch.

    Uses a pre-cached schedule dump at
    `output/briefs/.cache/past_schedules.json` (generated by
    `python3 -m src.brief cache-past-schedules`) to avoid fetching
    40+ schedules per runner. Falls back to live fetch if the cache
    is missing.
    """
    org = org or os.getenv("HORARO_ORG", "esa")
    current_slugs = set(_csv_env("HORARO_SCHEDULES", ""))
    pin = _csv_env("HORARO_PAST_SCHEDULES", "")
    all_schedules = _past_event_schedules(org, current_slugs)
    if pin:
        pin_set = set(pin)
        all_schedules = [s for s in all_schedules if s.get("slug") in pin_set]

    # Load pre-cached schedule data if available
    past_cache_path = os.path.join(CACHE_DIR, "past_schedules.json")
    past_cache: dict = {}
    if os.path.exists(past_cache_path):
        try:
            with open(past_cache_path) as f:
                past_cache = json.load(f)
        except (json.JSONDecodeError, OSError):
            past_cache = {}

    matches: list[dict] = []
    events: set[str] = set()
    first_appearance: dict | None = None
    error: str | None = None

    for sched in all_schedules:
        slug = sched.get("slug", "")
        cached = past_cache.get(slug)
        if cached and cached.get("items"):
            items = cached["items"]
            for item in items:
                if not _item_mentions_runner(item, name, twitch):
                    continue
                events.add(slug)
                entry = {
                    "event_slug": slug,
                    "event_name": cached.get("name", sched.get("name", "")),
                    "event_start": cached.get("start", sched.get("start", "")),
                    "scheduled": item.get("scheduled", ""),
                    "game": item.get("game", ""),
                    "category": item.get("category", ""),
                    "estimate": item.get("estimate", ""),
                    "stream": item.get("stream", ""),
                    "match": "twitch" if (twitch and twitch.lower() in (item.get("players", "") or "").lower()) else "name",
                }
                matches.append(entry)
                if first_appearance is None or entry["scheduled"] < first_appearance["scheduled"]:
                    first_appearance = entry
        else:
            # Live fetch fallback
            try:
                schedule = fetch_schedule(org, slug)
            except Exception as e:
                error = f"horaro fetch failed: {type(e).__name__}: {e}"
                continue
            for item in schedule.items:
                if not item.mentions_runner(name, twitch):
                    continue
                events.add(slug)
                entry = {
                    "event_slug": slug,
                    "event_name": sched.get("name", ""),
                    "event_start": sched.get("start", ""),
                    "scheduled": item.scheduled.isoformat(),
                    "game": item.game,
                    "category": item.category,
                    "estimate": item.estimate_str,
                    "stream": item.stream,
                    "match": "twitch" if (twitch and twitch.lower() in (item.players or "").lower()) else "name",
                }
                matches.append(entry)
                if first_appearance is None or item.scheduled.isoformat() < first_appearance["scheduled"]:
                    first_appearance = entry

    matches.sort(key=lambda m: m.get("scheduled", ""))
    return {
        "events": sorted(events),
        "matches": matches,
        "first_appearance": first_appearance,
        "error": error,
    }


def _item_mentions_runner(item: dict, name: str, twitch: str) -> bool:
    """Check if a cached schedule item mentions the runner.

    Mirrors ScheduleItem.mentions_runner but operates on the
    pre-cached dict format (game, players, category, ...).
    """
    if not name and not twitch:
        return False
    name_lower = (name or "").strip().lower()
    twitch_lower = (twitch or "").strip().lower()
    players = item.get("players", "") or ""
    players_lower = players.lower()
    # Check markdown link names
    for raw in re.findall(r"\[([^\]]+)\]\([^)]+\)", players):
        if name_lower and raw.strip().lower() == name_lower:
            return True
    # Check word-boundary substring
    if name_lower and re.search(rf"\b{re.escape(name_lower)}\b", players_lower):
        return True
    # Check twitch URL
    if twitch_lower and twitch_lower in players_lower:
        return True
    return False


def cmd_past_esa(args) -> None:
    """Find every past ESA event where this runner appeared.

    Primary source: lineup.esamarathon.dev (authoritative counts and
    event list, refreshed every 24h on disk). Fallback: horaro.net
    schedule scan (slower, finds events lineup doesn't track). The
    response marks which sources contributed so the brief can cite
    them honestly.
    """
    name = args.name or ""
    twitch = args.twitch or ""
    org = args.org or os.getenv("HORARO_ORG", "esa")

    sources_used: list[str] = []
    lineup_records = []
    lineup_error: str | None = None
    try:
        lineup = _load_lineup_cache()
        lineup_records = _lineup_lookup(lineup, name, twitch)
    except Exception as e:
        lineup_error = f"{type(e).__name__}: {e}"
        lineup_records = []

    lineup_record = lineup_records[0] if lineup_records else None
    lineup_events: list[str] = list(lineup_record.get("events", [])) if lineup_record else []
    lineup_runs: int = int(lineup_record.get("runs", 0)) if lineup_record else 0
    lineup_country: str = lineup_record.get("country", "") if lineup_record else ""

    if lineup_record:
        sources_used.append("lineup.esamarathon.dev")
    else:
        if lineup_error:
            sources_used.append(f"lineup.esamarathon.dev (error: {lineup_error})")

    # Horaro fallback — always run it for per-run detail (game/category)
    # even when lineup is the primary source for counts.
    horaro = _horaro_past_appearances(name, twitch, org)
    if horaro["events"]:
        if "horaro.net" not in sources_used:
            sources_used.append("horaro.net")
        if horaro.get("error"):
            sources_used.append(f"horaro.net (error: {horaro['error']})")

    # Merge: use lineup's event list as the canonical "events attended",
    # but use horaro's per-run matches to build a game+category timeline.
    # event_count is whichever source is authoritative.
    events_attended = lineup_events if lineup_record else horaro["events"]
    event_count = len(events_attended)
    first_event_year = _first_event_year(events_attended)

    # Appearance count: lineup's `runs` field is the authoritative
    # submission count; horaro's `matches` count is a per-schedule-item
    # tally which is usually lower (one row per submission slot).
    if lineup_record:
        appearance_count = lineup_runs
        first_appearance = {
            "event_slug": "",
            "event_name": events_attended[0] if events_attended else "",
            "event_start": "",
            "scheduled": "",
            "game": "",
            "category": "",
            "estimate": "",
            "stream": "",
            "match": "lineup",
        } if events_attended else None
    else:
        appearance_count = len(horaro["matches"])
        first_appearance = horaro["first_appearance"]

    # Fill first_appearance game/category from horaro if lineup-only
    if lineup_record and horaro["matches"] and first_appearance:
        # Find the earliest horaro match
        earliest = horaro["matches"][0] if horaro["matches"] else None
        if earliest:
            first_appearance["game"] = earliest.get("game", "")
            first_appearance["category"] = earliest.get("category", "")
            first_appearance["estimate"] = earliest.get("estimate", "")
            first_appearance["scheduled"] = earliest.get("scheduled", "")
            first_appearance["event_slug"] = earliest.get("event_slug", "")
            first_appearance["event_start"] = earliest.get("event_start", "")
            first_appearance["stream"] = earliest.get("stream", "")

    # ── ESA runs aggregation ──
    # Count how many times each game+category appears in horaro matches.
    esa_games: dict[str, dict] = {}
    for m in horaro["matches"]:
        g = m.get("game", "") or ""
        cat = m.get("category", "") or ""
        # Strip markdown links from game name for cleaner display
        clean_game = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", g).strip()
        key = f"{clean_game}|{cat}"
        if key not in esa_games:
            esa_games[key] = {
                "game": clean_game,
                "category": cat,
                "count": 0,
                "events": [],
            }
        esa_games[key]["count"] += 1
        ev = m.get("event_slug", "") or m.get("event_name", "") or ""
        if ev and ev not in esa_games[key]["events"]:
            esa_games[key]["events"].append(ev)

    esa_runs_list = sorted(esa_games.values(), key=lambda x: -x["count"])
    esa_game_count = len(set(g["game"] for g in esa_runs_list))
    esa_category_count = len(esa_runs_list)

    result = {
        "name": name,
        "twitch": twitch,
        "event_count": event_count,
        "appearance_count": appearance_count,
        "first_event": events_attended[0] if events_attended else None,
        "first_event_year": first_event_year,
        "events": events_attended,
        "first_appearance": first_appearance,
        "matches": horaro["matches"],
        "esa_runs": esa_runs_list,
        "esa_game_count": esa_game_count,
        "esa_category_count": esa_category_count,
        "country": lineup_country,
        "country_name": _country_name(lineup_country) if lineup_country else "",
        "sources_used": sources_used,
        "lineup_url": "https://lineup.esamarathon.dev/api/public" if lineup_record else None,
    }
    print(json.dumps(result, indent=2))


def _compose_stats(
    *,
    name: str,
    twitch: str,
    past_esa: dict,
    tenure: dict,
    communities: list[dict],
    personal_bests: list[dict],
    src_url: str | None,
    verified: bool,
    confidence: str | None,
) -> dict:
    """Build the {summary, stats, sources, errors} object for a runner.

    Pure: takes already-fetched data. Used by `cmd_runner_profile`
    and `sync_runner_profiles_to_db`. `errors` is a
    list[str] for any field that was unavailable; `summary` always
    carries every headline number (None when not available) so the
    web viewer can render placeholders.
    """
    pbs = personal_bests or []
    game_count = len(pbs)
    category_count = sum(len(g.get("times", [])) for g in pbs)
    top_games = [g.get("game_name", "") for g in pbs[:5] if g.get("game_name")]

    country = past_esa.get("country", "") or ""
    country_name = past_esa.get("country_name", "") or ""
    first_event = past_esa.get("first_event") or ""
    first_event_year = past_esa.get("first_event_year")
    years_active = None
    if first_event_year:
        years_active = max(0, _now().year - first_event_year)

    esa_runs = past_esa.get("esa_runs", [])
    esa_game_count = past_esa.get("esa_game_count", 0)
    esa_category_count = past_esa.get("esa_category_count", 0)
    esa_top_games = list(dict.fromkeys(g["game"] for g in esa_runs))[:5]

    summary = {
        "event_count": past_esa.get("event_count", 0),
        "appearance_count": past_esa.get("appearance_count", 0),
        "first_event": first_event or None,
        "first_event_year": first_event_year,
        "years_active": years_active,
        "pb_count": category_count,
        "pb_game_count": game_count,
        "src_tenure_years": tenure.get("years") if tenure.get("available") else None,
        "community_count": len(communities),
        "country_code": country.upper() if country else None,
        "country_name": country_name or None,
        "esa_game_count": esa_game_count,
        "esa_category_count": esa_category_count,
    }

    stats = {
        "past_esa": {
            "event_count": past_esa.get("event_count", 0),
            "appearance_count": past_esa.get("appearance_count", 0),
            "first_event": first_event or None,
            "first_event_year": first_event_year,
            "events": past_esa.get("events", []),
            "first_appearance": past_esa.get("first_appearance"),
            "esa_runs": esa_runs,
            "esa_game_count": esa_game_count,
            "esa_category_count": esa_category_count,
            "esa_top_games": esa_top_games,
            "sources": past_esa.get("sources_used", []),
            "verified": bool(past_esa.get("event_count", 0) or past_esa.get("appearance_count", 0)),
        },
        "tenure": tenure,
        "communities": communities,
        "country": {
            "code": country.upper() if country else None,
            "name": country_name or None,
            "source": "lineup.esamarathon.dev" if country else None,
            "confidence": "unverified" if country else None,
        } if country else {"code": None, "name": None, "source": None, "confidence": None},
        "personal_bests": {
            "game_count": game_count,
            "category_count": category_count,
            "top_games": top_games,
        },
    }

    sources: list[dict] = []
    if past_esa.get("lineup_url"):
        sources.append({"name": "lineup.esamarathon.dev", "url": past_esa["lineup_url"]})
    if "horaro.net" in (past_esa.get("sources_used") or []):
        org = os.getenv("HORARO_ORG", "esa")
        sources.append({"name": "horaro.net", "url": f"https://horaro.net/{org}"})
    if src_url:
        sources.append({"name": "speedrun.com", "url": src_url})

    errors: list[str] = []
    if not stats["past_esa"]["verified"]:
        errors.append("past_esa: no record in lineup or horaro")
    if not tenure.get("available"):
        errors.append("tenure: SRC signup unavailable")
    if not communities:
        errors.append("communities: no community markers found in SRC aboutme")
    if not pbs:
        errors.append("personal_bests: no SRC PBs found")

    return {
        "summary": summary,
        "stats": stats,
        "sources": sources,
        "errors": errors,
        "verified": verified,
        "confidence": confidence,
    }


def _fetch_runner_profile(
    name: str,
    twitch: str,
    *,
    use_cache: bool = True,
) -> dict:
    """Build the composite profile for one runner.

    Pulls past ESA from lineup (horaro fallback), tenure + communities
    + PBs from speedrun.com. Caches the result to disk for
    RUNNER_PROFILE_TTL_HOURS unless `use_cache` is False. Errors are
    captured per-source and returned in the `errors` list so the
    caller can decide how to render them.
    """
    cache = _load_runner_profile_cache()
    key = _runner_profile_key(twitch, name)
    cached = cache.get(key) if use_cache else None
    if cached and _runner_profile_is_fresh(cached):
        # Return a deep copy so the caller can mutate freely
        return json.loads(json.dumps(cached))

    # ── past ESA: prefer lineup, fall back to horaro ──
    pa_args = argparse.Namespace(name=name, twitch=twitch, org="")
    past_esa: dict = {}
    try:
        import io
        from contextlib import redirect_stdout
        buf = io.StringIO()
        with redirect_stdout(buf):
            cmd_past_esa(pa_args)
        past_esa = json.loads(buf.getvalue())
    except Exception as e:
        past_esa = {
            "event_count": 0, "appearance_count": 0,
            "first_event": None, "first_event_year": None,
            "events": [], "first_appearance": None, "matches": [],
            "country": "", "country_name": "", "sources_used": [],
            "lineup_url": None, "error": str(e),
        }

    # ── SRC: tenure, aboutme, PBs ──
    src: dict = {}
    rr_args = argparse.Namespace(twitch=twitch, name=name)
    try:
        import io
        from contextlib import redirect_stdout
        buf = io.StringIO()
        with redirect_stdout(buf):
            cmd_research_runner(rr_args)
        src = json.loads(buf.getvalue())
    except Exception:
        src = {"verified": False, "tenure": {"available": False},
               "personal_bests": [], "aboutme": None, "src_url": None,
               "confidence": None}

    tenure = src.get("tenure") or {"available": False, "label": "Not found — ask the runner."}
    communities = _extract_communities(src.get("aboutme"), None)

    profile = _compose_stats(
        name=name,
        twitch=twitch,
        past_esa=past_esa,
        tenure=tenure,
        communities=communities,
        personal_bests=src.get("personal_bests", []),
        src_url=src.get("src_url"),
        verified=src.get("verified", False),
        confidence=src.get("confidence"),
    )
    profile["name"] = name
    profile["twitch"] = twitch
    profile["fetched_at"] = _now().isoformat()

    # Persist to disk cache (best-effort)
    cache[key] = profile
    _save_runner_profile_cache(cache)
    return profile


def cmd_runner_profile(args) -> None:
    """Compose past-ESA + tenure + communities + PBs into one JSON.

    This is the primary entry point for the runner-brief workflow.
    Each field is filled from a deterministic source (lineup +
    horaro for past events, SRC /users/{id} for tenure and aboutme,
    SRC personal-bests for the games list). When a field cannot be
    filled, the corresponding key carries an `unavailable: true` flag
    so the brief can mark "not found — ask the runner" rather than
    fabricating data.

    Honors a 7-day on-disk cache so a 200-run batch doesn't re-fetch
    lineup/SRC for every runner. `--refresh` forces a recompute.
    """
    name = args.name or ""
    twitch = args.twitch or ""
    use_cache = not getattr(args, "refresh", False)

    profile = _fetch_runner_profile(name, twitch, use_cache=use_cache)
    print(json.dumps(profile, indent=2))


def cmd_siblings(args) -> None:
    """Find ESA sibling runs for a runner."""
    runs = _load_runs(args)
    result = xr.find_runner_sibling_runs(
        runs=runs,
        twitch=args.twitch,
        display_name=args.name,
        exclude_submission_id=args.exclude_submission_id or "",
    )
    print(json.dumps(result, indent=2))


def cmd_cache_past_schedules(args) -> None:
    """Pre-fetch and cache all past Horaro schedules.

    The cached dump at output/briefs/.cache/past_schedules.json is
    used by `_horaro_past_appearances` to avoid fetching 40+
    schedules per runner. Run this once before a batch of
    runner-profile calls.
    """
    org = args.org or os.getenv("HORARO_ORG", "esa")
    current_slugs = set(_csv_env("HORARO_SCHEDULES", ""))
    pin = _csv_env("HORARO_PAST_SCHEDULES", "")
    all_schedules = _past_event_schedules(org, current_slugs)
    if pin:
        pin_set = set(pin)
        all_schedules = [s for s in all_schedules if s.get("slug") in pin_set]

    cache: dict[str, dict] = {}
    errors: list[str] = []
    for s in all_schedules:
        slug = s.get("slug", "")
        try:
            sched = fetch_schedule(org, slug)
            items = []
            for it in sched.items:
                items.append({
                    "game": it.game,
                    "players": it.players,
                    "category": it.category,
                    "scheduled": it.scheduled.isoformat(),
                    "estimate": it.estimate_str,
                    "stream": it.stream,
                })
            cache[slug] = {
                "name": sched.name,
                "start": sched.start.isoformat(),
                "items": items,
            }
        except Exception as e:
            errors.append(f"{slug}: {type(e).__name__}: {e}")
            cache[slug] = {
                "name": s.get("name", ""),
                "start": s.get("start", ""),
                "items": [],
                "error": str(e),
            }

    os.makedirs(CACHE_DIR, exist_ok=True)
    path = os.path.join(CACHE_DIR, "past_schedules.json")
    with open(path, "w") as f:
        json.dump(cache, f, indent=2)

    result = {
        "cached": len(cache),
        "total_items": sum(len(v.get("items", [])) for v in cache.values()),
        "errors": errors,
        "path": path,
    }
    print(json.dumps(result, indent=2))


def cmd_cache_developer(args) -> None:
    """Write a developer cache entry."""
    cache = _load_developer_cache()
    cache[args.game] = args.developer
    _save_developer_cache(cache)
    print(json.dumps({"ok": True, "game": args.game, "developer": args.developer}))


def cmd_find_siblings(args) -> None:
    """Find other schedule games by the same developer."""
    cache = _load_developer_cache()
    developer = args.developer

    # Find all games in cache with this developer
    cached_games = [g for g, d in cache.items() if d.lower() == developer.lower()]

    # Cross-reference with schedule
    runs = _load_runs(args)
    schedule_games = set(r.game for r in runs)

    siblings = [g for g in cached_games if g in schedule_games]

    print(json.dumps({
        "developer": developer,
        "sibling_games": siblings,
    }, indent=2))


def cmd_write(args) -> None:
    """Write a brief markdown file + JSON sidecar.

    Preserves HOST NOTES block from previous write unless --force is set.
    Pass markdown content via --md (string) and structured data via --data (JSON).
    """
    _ensure_dirs()

    slug = args.slug
    md_content = args.md or ""
    json_data = json.loads(args.data) if args.data else {}

    md_path = os.path.join(BRIEFS_DIR, f"{slug}.md")
    json_path = os.path.join(BRIEFS_DIR, f"{slug}.json")

    host_notes_preserved = False

    # Read existing file for HOST NOTES
    if not getattr(args, "force", False) and os.path.exists(md_path):
        try:
            with open(md_path) as f:
                existing = f.read()
            start = existing.find("<!-- HOST NOTES -->")
            end = existing.find("<!-- /HOST NOTES -->")
            if start != -1 and end != -1:
                host_notes = existing[start:end + len("<!-- /HOST NOTES -->")]
                md_content += "\n\n" + host_notes
                host_notes_preserved = True
        except OSError:
            pass

    with open(md_path, "w") as f:
        f.write(md_content.strip() + "\n")

    with open(json_path, "w") as f:
        json.dump(json_data, f, indent=2)

    print(json.dumps({
        "md_file": md_path,
        "json_file": json_path,
        "host_notes_preserved": host_notes_preserved,
    }, indent=2))


def cmd_orphans(args) -> None:
    """Scan brief files directory, mark files whose runs no longer exist in schedule."""
    brief_dir = args.dir or BRIEFS_DIR
    if not os.path.isdir(brief_dir):
        print(json.dumps({"marked": [], "error": f"Directory not found: {brief_dir}"}))
        return

    all_runs = _load_runs(args)
    active_slugs = set()
    for r in all_runs:
        scheduled = r.scheduled
        if scheduled.tzinfo is None:
            scheduled = scheduled.replace(tzinfo=TZ)
        slug = run_slug(r.game, r.category, scheduled, r.submission_id or "")
        active_slugs.add(slug)

    marked = []
    for fname in os.listdir(brief_dir):
        if not fname.endswith(".md") or fname == "_index.md":
            continue
        slug = fname[:-3]  # strip .md
        if slug in active_slugs:
            continue
        # Check if it's a directory (shift dir)
        fpath = os.path.join(brief_dir, fname)
        if os.path.isdir(fpath):
            continue
        if not os.path.isfile(fpath):
            continue
        # Mark orphan
        try:
            with open(fpath) as f:
                content = f.read()
        except OSError:
            continue
        if content.startswith("<!-- ORPHAN"):
            continue  # already marked
        marked.append({
            "file": fname,
            "slug": slug,
        })
        with open(fpath, "w") as f:
            now_str = _now().strftime("%Y-%m-%d %H:%M")
            f.write(f"<!-- ORPHAN: This run is no longer in the schedule (last seen {now_str}) -->\n")
            f.write(content)

    print(json.dumps({"marked": marked}, indent=2))


def cmd_stale(args) -> None:
    """Check spreadsheet staleness."""
    if getattr(args, "source", "xlsx") == "db":
        db_path = getattr(args, "db_path", "") or "output/esa.db"
        result = xr.check_stale_from_db(db_path, args.max_age_hours)
    else:
        result = xr.check_stale(args.spreadsheet, args.max_age_hours)
    print(json.dumps(result, indent=2))


# ── Lift functions for admin sync ──


def generate_briefs(
    spreadsheet_path: str = "",
    briefs_dir: str = "",
    source: str = "xlsx",
    db_path: str = "",
) -> dict:
    """Regenerate all brief markdown files from the spreadsheet (or DB).

    Runner history is not embedded in run briefs; it lives on the runner
    profile page (GET /api/runners/{slug}/profile).
    Returns a summary dict with brief count and any errors.
    Reads env vars as defaults for empty parameters.
    """
    import os
    if not spreadsheet_path:
        spreadsheet_path = os.environ.get("SPREADSHEET_PATH", SPREADSHEET_PATH)
    if not briefs_dir:
        briefs_dir = os.environ.get("BRIEFS_DIR", BRIEFS_DIR)
    if not db_path:
        db_path = os.environ.get("DB_PATH", "output/esa.db")

    _ensure_dirs()

    if source == "db":
        runs = xr.read_cross_reference_from_db(db_path)
    else:
        runs = xr.read_cross_reference(spreadsheet_path)
    count = 0
    errors = []

    for r in runs:
        scheduled = r.scheduled
        if scheduled.tzinfo is None:
            scheduled = scheduled.replace(tzinfo=TZ)
        slug = run_slug(r.game, r.category, scheduled, r.submission_id or "")

        try:
            md_content, json_data = bb.build_brief(r, spreadsheet_path)

            md_path = os.path.join(briefs_dir, f"{slug}.md")
            json_path = os.path.join(briefs_dir, f"{slug}.json")

            with open(md_path, "w") as f:
                f.write(md_content.strip() + "\n")
            with open(json_path, "w") as f:
                json.dump(json_data, f, indent=2)

            count += 1
        except Exception as e:
            errors.append({"slug": slug, "error": str(e)})

    return {"count": count, "errors": errors}


def research_runner(
    twitch: str = "",
    name: str = "",
    use_cache: bool = True,
) -> dict:
    """Fetch runner profile from SRC with tiered verification.

    Returns the runner profile dict (same shape as cmd_runner_profile).
    """
    return _fetch_runner_profile(name, twitch, use_cache=use_cache)


def generate_briefs_llm(
    db_path: str = "",
    briefs_dir: str = "",
    mode: str = "scan",
    max_concurrency: int = 0,
    refresh_runners: bool = False,
    slugs: list[str] | None = None,
    runner_twitches: list[str] | None = None,
) -> dict:
    """Regenerate brief markdown + JSON files using an LLM for prose authoring.

    DB is the authoritative source.  Deterministic sidecar (incentives,
    siblings, SRC records, confidence flags) is assembled by build_brief();
    the LLM only writes the prose.  Runner profiles are fetched from the
    on-disk cache (refreshed first when refresh_runners=True).

    Safety: a DB snapshot and a backup of the briefs dir are created before
    any files are written.

    Args:
        db_path: Path to the SQLite DB (default: DB_PATH env or output/esa.db).
        briefs_dir: Output directory for brief files (default: BRIEFS_DIR env or output/briefs).
        mode: "scan" | "interview" | "full" (default: "scan").
        max_concurrency: Max parallel LLM calls (default: LLM_MAX_CONCURRENCY env or 4).
        refresh_runners: If True, refresh runner profiles from SRC before
            generating briefs (scoped to matched runners when slugs/runner_twitches
            are supplied, otherwise all runners — slow).
        slugs: Optional list of run slugs to regenerate. When supplied only
            those runs are processed; all others are skipped.
        runner_twitches: Optional list of Twitch handles (lowercase). When
            supplied only runs whose primary runner matches are processed.
            Can be combined with ``slugs`` (union).

    Returns:
        {"count": N, "runner_profiles_updated": N, "errors": [...]}
    """
    import shutil
    import concurrent.futures
    from datetime import datetime as _dt

    from . import brief_prompts as bp
    from . import llm_client
    from .import_to_sqlite import sync_runner_profiles_to_db

    if not db_path:
        db_path = os.environ.get("DB_PATH", "output/esa.db")
    if not briefs_dir:
        briefs_dir = os.environ.get("BRIEFS_DIR", BRIEFS_DIR)
    if not max_concurrency:
        max_concurrency = int(os.environ.get("LLM_MAX_CONCURRENCY", "4"))

    _ensure_dirs()

    # ── Safety: snapshot DB + backup briefs dir ──────────────────────────────
    from . import snapshot as snap
    from . import audit as audit_log
    from .db import get_schema_version

    output_dir = os.path.dirname(db_path)
    if os.path.exists(db_path):
        schema_v = get_schema_version(db_path)
        snap.create_snapshot(db_path, schema_v, reason="pre-brief-llm")
        audit_log.write_audit(output_dir, "generate_briefs_llm", "snapshot created pre-brief-llm")

    if os.path.isdir(briefs_dir):
        ts = _dt.now(TZ).strftime("%Y%m%dT%H%M%S")
        backup_dir = briefs_dir.rstrip("/") + f".bak.{ts}"
        shutil.copytree(briefs_dir, backup_dir)
        audit_log.write_audit(output_dir, "generate_briefs_llm", f"briefs backed up to {backup_dir}")

    # ── Optionally refresh runner profiles from SRC ──────────────────────────
    if refresh_runners:
        all_runs_for_refresh = xr.read_cross_reference_from_db(db_path)
        seen: set[str] = set()
        for r in all_runs_for_refresh:
            twitch = (r.runner_twitch or "").strip().lower()
            name = (r.runner_display or "").strip()
            key = twitch or name
            if not key or key in seen:
                continue
            # Scope refresh to matched runners when filters are supplied
            if runner_twitches and twitch not in {t.strip().lower() for t in runner_twitches}:
                continue
            seen.add(key)
            try:
                _fetch_runner_profile(name, twitch, use_cache=False)
            except Exception:
                pass
        audit_log.write_audit(output_dir, "generate_briefs_llm", f"refreshed profiles for {len(seen)} runners")

    # Sync refreshed profiles into the DB
    sync_result = sync_runner_profiles_to_db(db_path)
    audit_log.write_audit(
        output_dir, "generate_briefs_llm",
        f"synced runner profiles to DB: updated={sync_result['updated']} skipped={sync_result['skipped']}",
    )

    # ── Pre-warm Horaro cache ────────────────────────────────────────────────
    try:
        cache_args = argparse.Namespace(org="")
        cmd_cache_past_schedules(cache_args)
    except Exception:
        pass  # Non-fatal; per-runner horaro fallback still works

    # ── Load all runs + incentives from DB ──────────────────────────────────
    runs = xr.read_cross_reference_from_db(db_path)
    all_incentives = xr.read_incentives_from_db(db_path)

    # ── Apply slug / runner filters ──────────────────────────────────────────
    slug_set: set[str] = {s.strip() for s in slugs} if slugs else set()
    twitch_set: set[str] = {t.strip().lower() for t in runner_twitches} if runner_twitches else set()

    if slug_set or twitch_set:
        filtered: list[xr.RunRow] = []
        for r in runs:
            scheduled = r.scheduled
            if scheduled.tzinfo is None:
                scheduled = scheduled.replace(tzinfo=TZ)
            r_slug = run_slug(r.game, r.category, scheduled, r.submission_id or "")
            r_twitch = (r.runner_twitch or "").strip().lower()
            if r_slug in slug_set or r_twitch in twitch_set:
                filtered.append(r)
        runs = filtered
        audit_log.write_audit(
            output_dir, "generate_briefs_llm",
            f"filtered to {len(runs)} run(s) (slugs={len(slug_set)} runner_twitches={len(twitch_set)})",
        )

    count = 0
    errors: list[dict] = []

    def _process_run(r: xr.RunRow) -> dict | None:
        """Build one brief with LLM prose. Returns error dict or None on success."""
        scheduled = r.scheduled
        if scheduled.tzinfo is None:
            scheduled = scheduled.replace(tzinfo=TZ)
        slug = run_slug(r.game, r.category, scheduled, r.submission_id or "")

        try:
            # Deterministic sidecar (DB-primary path)
            md_fallback, json_data = bb.build_brief(
                r,
                incentives=all_incentives,
                all_runs=runs,
            )

            # LLM prose (falls back to deterministic md if LLM_DISABLED)
            # Runner history is NOT passed — it belongs on the runner page.
            user_prompt = bp.build_user_prompt(
                mode=mode,
                run_meta=json_data.get("run_meta", {}),
                sidecar=json_data,
            )
            prose = llm_client.complete(
                system=bp.SYSTEM_PROMPT,
                user=user_prompt,
                disabled_fallback=md_fallback,
            )

            json_data["mode"] = mode

            md_path = os.path.join(briefs_dir, f"{slug}.md")
            json_path = os.path.join(briefs_dir, f"{slug}.json")

            with open(md_path, "w") as f:
                f.write(prose.strip() + "\n")
            with open(json_path, "w") as f:
                json.dump(json_data, f, indent=2)

            return None  # success

        except Exception as exc:
            return {"slug": slug, "error": str(exc)}

    # ── Bounded-concurrency execution ────────────────────────────────────────
    with concurrent.futures.ThreadPoolExecutor(max_workers=max_concurrency) as pool:
        futures = {pool.submit(_process_run, r): r for r in runs}
        for future in concurrent.futures.as_completed(futures):
            result = future.result()
            if result is None:
                count += 1
            else:
                errors.append(result)

    audit_log.write_audit(
        output_dir, "generate_briefs_llm",
        f"completed: {count} briefs written, {len(errors)} errors",
    )

    return {
        "count": count,
        "runner_profiles_updated": sync_result.get("updated", 0),
        "errors": errors,
    }


def cmd_generate_llm(args) -> None:
    """CLI handler for the generate-llm subcommand."""
    slugs = [s.strip() for s in args.slugs.split(",") if s.strip()] if getattr(args, "slugs", "") else None
    runners = [r.strip() for r in args.runner.split(",") if r.strip()] if getattr(args, "runner", "") else None
    result = generate_briefs_llm(
        db_path=getattr(args, "db_path", "") or os.environ.get("DB_PATH", "output/esa.db"),
        briefs_dir=getattr(args, "briefs_dir", "") or os.environ.get("BRIEFS_DIR", BRIEFS_DIR),
        mode=getattr(args, "mode", "scan"),
        max_concurrency=getattr(args, "max_concurrency", 0),
        refresh_runners=getattr(args, "refresh_runners", False),
        slugs=slugs,
        runner_twitches=runners,
    )
    print(json.dumps(result, indent=2))


# ── CLI parser ───────────────────────────────────────────────────────────────


def main() -> None:
    parser = argparse.ArgumentParser(
        description="ESA Host Brief: generate run briefs from schedule + SRC data",
    )
    parser.add_argument(
        "--spreadsheet", default=SPREADSHEET_PATH,
        help=f"Path to incentive plan XLSX (default: {SPREADSHEET_PATH})",
    )
    parser.add_argument(
        "--source", default="xlsx", choices=["xlsx", "db"],
        help="Data source: xlsx (default) or db (SQLite). When 'db', also set --db-path or DB_PATH env var.",
    )
    parser.add_argument(
        "--db-path", default=os.getenv("DB_PATH", "output/esa.db"),
        help="Path to SQLite DB (default: DB_PATH env or output/esa.db)",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    # picker
    p_picker = sub.add_parser("picker", help="Interactive pick list of upcoming runs")
    p_picker.add_argument("--stream", default="", help="Filter by stream token")
    p_picker.set_defaults(func=cmd_picker)

    # runs
    p_runs = sub.add_parser("runs", help="List runs by time window")
    p_runs.add_argument("--window", default="", help="ISO window: start/end (e.g. 2026-08-01T14:00/2026-08-01T18:00)")
    p_runs.add_argument("--next", type=float, default=0, dest="next_hours", help="Next N hours")
    p_runs.add_argument("--marathon", action="store_true", help="All marathon runs")
    p_runs.add_argument("--stream", default="", help="Filter by stream token")
    p_runs.set_defaults(func=cmd_runs)

    # research
    p_res = sub.add_parser("research", help="Fetch SRC categories + records for a game")
    p_res.add_argument("--game", required=True)
    p_res.add_argument("--category", default="")
    p_res.add_argument("--estimate-min", type=int, default=0, dest="estimate_min")
    p_res.set_defaults(func=cmd_research)

    # research-runner
    p_rr = sub.add_parser("research-runner", help="Look up runner on SRC")
    p_rr.add_argument("--twitch", default="")
    p_rr.add_argument("--name", default="")
    p_rr.set_defaults(func=cmd_research_runner)

    # past-esa
    p_pe = sub.add_parser("past-esa", help="Find past ESA Horaro appearances")
    p_pe.add_argument("--twitch", default="")
    p_pe.add_argument("--name", default="")
    p_pe.add_argument("--org", default="")
    p_pe.set_defaults(func=cmd_past_esa)

    # runner-profile (composes research-runner + past-esa + communities)
    p_rp = sub.add_parser(
        "runner-profile",
        help="Composite runner profile: past ESA + tenure + communities + PBs",
    )
    p_rp.add_argument("--twitch", default="")
    p_rp.add_argument("--name", default="")
    p_rp.add_argument(
        "--refresh", action="store_true",
        help="Bypass the 7-day on-disk cache and recompute from sources",
    )
    p_rp.set_defaults(func=cmd_runner_profile)

    # siblings
    p_sib = sub.add_parser("siblings", help="Find ESA sibling runs for a runner")
    p_sib.add_argument("--twitch", default="")
    p_sib.add_argument("--name", default="")
    p_sib.add_argument("--exclude-submission-id", default="")
    p_sib.set_defaults(func=cmd_siblings)

    # cache-past-schedules
    p_cps = sub.add_parser(
        "cache-past-schedules",
        help="Pre-fetch all past Horaro schedules into a local cache",
    )
    p_cps.add_argument("--org", default="")
    p_cps.set_defaults(func=cmd_cache_past_schedules)

    # cache-developer
    p_cd = sub.add_parser("cache-developer", help="Write developer cache entry")
    p_cd.add_argument("--game", required=True)
    p_cd.add_argument("--developer", required=True)
    p_cd.set_defaults(func=cmd_cache_developer)

    # find-siblings
    p_fs = sub.add_parser("find-siblings", help="Find scheduled games by developer")
    p_fs.add_argument("--developer", required=True)
    p_fs.set_defaults(func=cmd_find_siblings)

    # write
    p_wr = sub.add_parser("write", help="Write brief .md + .json sidecar")
    p_wr.add_argument("--slug", required=True)
    p_wr.add_argument("--md", help="Markdown brief content")
    p_wr.add_argument("--data", help="JSON sidecar data (serialized)")
    p_wr.add_argument("--force", action="store_true", help="Overwrite HOST NOTES too")
    p_wr.set_defaults(func=cmd_write)

    # orphans
    p_or = sub.add_parser("orphans", help="Check and mark orphaned brief files")
    p_or.add_argument("--dir", default=BRIEFS_DIR, help="Briefs directory")
    p_or.set_defaults(func=cmd_orphans)

    # stale
    p_st = sub.add_parser("stale", help="Check spreadsheet staleness")
    p_st.add_argument("--max-age-hours", type=float, default=6.0, dest="max_age_hours")
    p_st.set_defaults(func=cmd_stale)

    # generate-llm
    p_gl = sub.add_parser(
        "generate-llm",
        help="Regenerate all briefs using an LLM (DB source, force overwrite)",
    )
    p_gl.add_argument(
        "--mode", default="scan", choices=["scan", "interview", "full"],
        help="Brief depth: scan (default), interview, or full",
    )
    p_gl.add_argument(
        "--db-path", default=os.getenv("DB_PATH", "output/esa.db"),
        dest="db_path", help="Path to SQLite DB",
    )
    p_gl.add_argument(
        "--briefs-dir", default=os.environ.get("BRIEFS_DIR", BRIEFS_DIR),
        dest="briefs_dir", help="Output directory for brief files",
    )
    p_gl.add_argument(
        "--max-concurrency", type=int, default=0, dest="max_concurrency",
        help="Max parallel LLM calls (default: LLM_MAX_CONCURRENCY env or 4)",
    )
    p_gl.add_argument(
        "--refresh-runners", action="store_true", dest="refresh_runners",
        help="Re-fetch runner profiles from SRC before generating briefs (scoped to --runner if supplied)",
    )
    p_gl.add_argument(
        "--slugs", default="",
        help="Comma-separated run slugs to regenerate (e.g. sm64__120-star__2026-08-01T1400). "
             "If omitted, all runs are processed.",
    )
    p_gl.add_argument(
        "--runner", default="",
        help="Comma-separated Twitch handle(s) — regenerate only runs whose primary runner matches. "
             "Can be combined with --slugs (union).",
    )
    p_gl.set_defaults(func=cmd_generate_llm)

    parsed = parser.parse_args()
    parsed.func(parsed)


if __name__ == "__main__":
    main()
